-- Definici�n del tipo JUGADOR
CREATE TYPE JUGADOR AS OBJECT (
  IDJUG NUMBER,
  USERNAME VARCHAR2(50),
  EMAIL VARCHAR2(50),
  MEMBER FUNCTION GET_IDJUG RETURN NUMBER, --encapsulamiento
  MEMBER FUNCTION GET_USERNAME RETURN VARCHAR2,--encapsulamiento
  MEMBER FUNCTION CALCULAR_PUNTAJE RETURN NUMBER --encapsulamiento
) NOT FINAL;

CREATE TYPE BODY JUGADOR AS
  MEMBER FUNCTION GET_IDJUG RETURN NUMBER IS
  BEGIN
    RETURN IDJUG;
  END;
  
  MEMBER FUNCTION GET_USERNAME RETURN VARCHAR2 IS
  BEGIN
    RETURN USERNAME;
  END;
  
  MEMBER FUNCTION CALCULAR_PUNTAJE RETURN NUMBER IS
  BEGIN
    RETURN 1;
  END CALCULAR_PUNTAJE;
END;

-- Definici�n del tipo JUGADOR_PREMIUM que hereda de JUGADOR
CREATE TYPE JUGADOR_PREMIUM UNDER JUGADOR ( //se utiliza UNDER en vez de extends
  BONIFICACION NUMBER,
  MEMBER FUNCTION GET_BONIFICACION RETURN NUMBER,
  OVERRIDING MEMBER FUNCTION CALCULAR_PUNTAJE RETURN NUMBER --polimorfismo se utiliza la misma funci�n pero en cada una tiene un calculo distinto
);

CREATE TYPE BODY JUGADOR_PREMIUM AS
  MEMBER FUNCTION GET_BONIFICACION RETURN NUMBER IS
  BEGIN
    RETURN BONIFICACION;
  END;
  
  OVERRIDING MEMBER FUNCTION CALCULAR_PUNTAJE RETURN NUMBER IS
  BEGIN
    RETURN 3 * BONIFICACION;
  END CALCULAR_PUNTAJE;

-- Definici�n del tipo JUGADOR_NORMAL que hereda de JUGADOR
CREATE TYPE JUGADOR_NORMAL UNDER JUGADOR (
  LIMITE NUMBER,
  MEMBER FUNCTION GET_LIMITE RETURN NUMBER,
  OVERRIDING MEMBER FUNCTION CALCULAR_PUNTAJE RETURN NUMBER
);

CREATE TYPE BODY JUGADOR_NORMAL AS
  MEMBER FUNCTION GET_LIMITE RETURN NUMBER IS
  BEGIN
    RETURN LIMITE;
  END;
  
  OVERRIDING MEMBER FUNCTION CALCULAR_PUNTAJE RETURN NUMBER IS
  BEGIN
    RETURN 3 * LIMITE;
  END CALCULAR_PUNTAJE;
END;

-- Creaci�n de la tabla TABLERO_MIEMBRO
CREATE TABLE TABLERO_MIEMBRO (
  jugador_p JUGADOR_NORMAL,
  fecha_ing DATE
);

-- Inserci�n de datos en la tabla TABLERO_MIEMBRO
INSERT INTO TABLERO_MIEMBRO VALUES (JUGADOR_NORMAL(11, 'hi', 'HI@HOTMAIL.COM', 11), SYSDATE);

-- Consulta para obtener lista de puntajes
SELECT J.jugador_p
.CALCULAR_PUNTAJE() AS Lista_puntaje
FROM TABLERO_MIEMBRO J;

-- Consulta para obtener lista de nombres
SELECT J.jugador_p.GET_USERNAME() AS Lista_jugadores
FROM TABLERO_MIEMBRO J;

-- Creaci�n de la tabla TABLERO_PREMIUM que hereda de JUGADOR_PREMIUM
CREATE TABLE TABLERO_PREMIUM OF JUGADOR_PREMIUM;

-- Inserci�n de datos en la tabla TABLERO_PREMIUM
INSERT INTO TABLERO_PREMIUM VALUES (JUGADOR_PREMIUM(12, 'BYE', 'BYE@HOTMAIL.COM', 20));
END;











